//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginReport) DeepCopyInto(out *PluginReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginReport.
func (in *PluginReport) DeepCopy() *PluginReport {
	if in == nil {
		return nil
	}
	out := new(PluginReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginReportList) DeepCopyInto(out *PluginReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PluginReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginReportList.
func (in *PluginReportList) DeepCopy() *PluginReportList {
	if in == nil {
		return nil
	}
	out := new(PluginReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginReportSpec) DeepCopyInto(out *PluginReportSpec) {
	*out = *in
	in.StartTimeStamp.DeepCopyInto(&out.StartTimeStamp)
	in.EndTimeStamp.DeepCopyInto(&out.EndTimeStamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginReportSpec.
func (in *PluginReportSpec) DeepCopy() *PluginReportSpec {
	if in == nil {
		return nil
	}
	out := new(PluginReportSpec)
	in.DeepCopyInto(out)
	return out
}

