=======
apiVersion: v1
kind: Namespace
metadata:
  name: wardle
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: apiserver
  namespace: wardle
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregated-apiserver-clusterrole
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-apiserver-clusterrolebinding
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: wardle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wardle:system:auth-delegator
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: wardle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wardle-auth-reader
  namespace: kube-system
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: wardle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
        - name: {{ .Values.spiderdoctorApiserver.name | trunc 63 | trimSuffix "-" }}
          image: {{ include "project.spiderdoctorApiserver.image" . | quote }}
          imagePullPolicy: {{ .Values.spiderdoctorApiserver.image.pullPolicy }}
          command:
            - /usr/bin/apiserver
          volumeMounts:
            {{- if .Values.feature.aggregateReport.enabled }}
            - name: report-data
              mountPath: /report
            {{- end }}
      volumes:
        {{- if .Values.feature.aggregateReport.enabled }}
        {{- if .Values.feature.aggregateReport.controller.pvc.enabled }}
        - name: report-data
          persistentVolumeClaim:
            claimName: {{ .Values.spiderdoctorApiserver.name | trunc 63 | trimSuffix "-" }}
        {{- else }}
        - name: report-data
          hostPath:
            path: {{ .Values.feature.aggregateReport.controller.reportHostPath }}
            type: DirectoryOrCreate
        {{- end }}
        {{- end }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.system.spiderdoctor.spidernet.io
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  insecureSkipTLSVerify: true
  group: system.spiderdoctor.spidernet.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: spiderdoctor-apiserver
    namespace: kube-system
  version: v1beta1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiderdoctor-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Values.spiderdoctorController.name | trunc 63 | trimSuffix "-" }}
      containers:
        - name: {{ .Values.spiderdoctorApiserver.name | trunc 63 | trimSuffix "-" }}
          image: {{ include "project.spiderdoctorApiserver.image" . | quote }}
          imagePullPolicy: {{ .Values.spiderdoctorApiserver.image.pullPolicy }}
          command:
            - /usr/bin/apiserver
          args:
            - --v=6
            - --etcd-servers=http://localhost:2379
        - name: etcd
          image: gcr.io/etcd-development/etcd:v3.5.7
---
apiVersion: v1
kind: Service
metadata:
  name: spiderdoctor-apiserver
  namespace: kube-system
  labels:
    {{- include "project.spiderdoctorApiserver.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    apiserver: "true"

