name: Auto CherryPick PR

permissions: write-all

env:
  LABEL_PREFIX_CHERRYPICK: "/cherry-pick"

on:
  pull_request:
    types:
      - opened
      - closed
  pull_request_target:
    types:
      - opened
      - closed

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          ALL_LABEL="${{ github.event.pull_request.labels.*.name }}"
          echo "ALL_LABEL=${ALL_LABEL}"
          ALL_COMMIT="${{ github.event.pull_request.commits }}"
          echo "ALL_COMMIT=${ALL_COMMIT}"
          
          





