name: CherryPick PR

permissions: write-all

env:
  LABEL_PREFIX_CHERRYPICK: "cherrypick-"

on:
  pull_request_target:
    types:
      - opened
      - closed

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: kceb/pull-request-url-action@v1
        id: pr-url

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: cherry pick
        run: |
          set -x
          echo "labels: ${{ steps.pr-labels.outputs.labels }}"
          echo "author: ${{ github.event.pull_request.user.login }}"
          #echo "GITHUB_REF: ${GITHUB_REF##*/}"
          echo "url: ${{ steps.pr-url.outputs.url }}"
          #echo "sha: ${{ github.sha }}"
          #echo "github.base_ref: ${{ github.base_ref }}"
          echo "pr branch name, github.head_ref: ${{ github.head_ref }}"
          #echo "github.ref: ${{ github.ref }}"
          #echo "github.ref_name: ${{ github.ref_name }}"
          #echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
          echo "pr latest commit, github.event.pull_request.head.sha = ${{ github.event.pull_request.head.sha }}"
          #--
          WATH_MERGE_BRANCH_LIST=""
          for LABEL in ${{ steps.pr-labels.outputs.labels }} ; do
              echo "checking lable $LABEL with ${{ matrix.label }} "
              PREFIX="${{ env.LABEL_PREFIX_CHERRYPICK }}"
              grep -E "^${echo}" <<< "${LABEL}" || continue
              BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
              WATH_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
          done
          [ -z "$WATH_MERGE_BRANCH_LIST" ] && echo "no need to cherry pick to ${{ matrix.releaseName }}" && exit 0
          echo "cherry pick to $WATH_MERGE_BRANCH_LIST "
          #--
          echo "============= it is required to cherry pick to ${{ matrix.releaseName }} ============"
          if [ ! -f "./tools/cherry/cherry.sh" ] ; then 
              echo "error ,there is no /tools/cherry/cherry.sh in branch ${{ matrix.releaseName }} "
              exit 1
          fi
          chmod +x ./tools/cherry/cherry.sh
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
          git config --global user.email "you@example.com"
          git config --global user.name "weizhou.lan"
          #export GIT_AUTHOR_NAME="weizhou.lan"
          #export GIT_AUTHOR_EMAIL="email@example.com"
          for BRANCH in ${$WATH_MERGE_BRANCH_LIST}; do
              echo "---- cherry for ${BRANCH}"
              git fetch origin ${BRANCH}:${BRANCH}
              git branch
          done
          exit 0
          #
          export CHERRY_FROM_BRANCH=${{ github.head_ref }}
          if ./tools/cherry/cherry.sh "${{ github.event.pull_request.head.sha }}" ; then
              echo "succeed to cherry pick"
          else
              echo "error, failed to cherry pick"
              exit 1
          fi
          #--- create pr
          #echo ${{ secrets.WELAN_PAT }} | gh auth login --with-token
          #gh pr  create --title 'test' --body 'sadf'  --base ${{ matrix.releaseName }}










