name: Auto CherryPick PR

permissions: write-all

env:
  LABEL_PREFIX_CHERRYPICK: "/cherry-pick"

on:
#  pull_request:
#    types:
#      - closed
  pull_request_target:
    types:
      - opened
      - closed



jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - releaseName: release-v0.2
            label: cherrypick-release-v0.2
          - releaseName: release-v0.2.5
            label: cherrypick-release-v0.2.5
          - releaseName: main
            label: cherrypick-main

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ matrix.releaseName }}

      - uses: kceb/pull-request-url-action@v1
        id: pr-url

      - name: cherry pick
        if: contains( github.event.pull_request.labels.*.name, '${{ matrix.label }}' )
        run: |
          echo "author: ${{ github.event.pull_request.user.login }}"
          echo "GITHUB_REF: ${GITHUB_REF##*/}"
          echo "url: ${{ steps.pr-url.outputs.url }}"
          echo "sha: ${{ github.sha }}"
          #--
          chmod +x ./tools/cherry/cherry.sh
          if ./tools/cherry/cherry.sh "${{ github.sha }}" ; then
              echo "succeed to cherry pick"
          else
              echo "error, failed to cherry pick"
              exit 1
          fi

